name: CI

on:
  push:
    branches: [ master, feature/dockerfile-preparations ]
  pull_request:
    branches: [ master, feature/dockerfile-preparations ]

  workflow_dispatch:

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: 588200329560
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: docker build
        run: |
          pwd
          ls -la ./
          CONTAINER_IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/coordinator:$TAG"
          echo $CONTAINER_IMAGE
          docker build -t $CONTAINER_IMAGE -f docker/Dockerfile .

      - name: Setup ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Login to AWS ECR
          $( aws ecr get-login --no-include-email )
